# Generated by Django 4.2.11 on 2024-03-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generatormodel',
            old_name='content',
            new_name='description',
        ),
    ]
